```{r library, include=FALSE}
my_packages <- c("tidyverse", "data.table")
pacman::p_load(char = my_packages)

tmp <- list()
```

# load
```{r}
load("Input/01/mRNA.Rda")
load("Input/02/drug.Rda")
load("Input/03/anno_0509.Rda")
```

# Change denglab's PDO
```{r}
table(drug_anno$ProjectID)
```

```{r}
table(sample_anno$ProjectID)
```
```{r}
drug_anno$ProjectID <- recode(drug_anno$ProjectID,
                             "deng1" = "UMPDO1",
                             "deng2" = "UMPDO2",
                             "deng3" = "UMPDO3")
sample_anno$ProjectID <- recode(sample_anno$ProjectID,
                             "UMPDO-PROJECT-1" = "UMPDO1",
                             "UMPDO-PROJECT-2" = "UMPDO2",
                             "UMPDO-PROJECT-3" = "UMPDO3")

# Verify the changes
table(sample_anno$ProjectID)
```

```{r}
sample_anno2 <- sample_anno
sample_anno2$ProjectRawName <- NULL
sample_anno <- sample_anno[!duplicated(sample_anno2),]

table(sample_anno$ProjectID)
```


```{r}
UMPDO1_mRNA <- deng1_mRNA
UMPDO1_drug <- deng1_drug
UMPDO2_mRNA <- deng2_mRNA
UMPDO2_drug <- deng2_drug
UMPDO3_mRNA <- deng3_mRNA
UMPDO3_drug <- deng3_drug
```

# Save
```{r}
save(drug_anno,
     sample_anno,
     file = "Input/03/anno_0510.Rda")
```

omics:
```{r}
save(
  ccle_mRNA,
  gdsc_mRNA,
  NCI60_mRNA,
  tavor_mRNA,
  UMPDO1_mRNA,
  UMPDO2_mRNA,
  UMPDO3_mRNA,
  Xeva_mRNA,
  file = "Input/01/mRNA.Rda"
)
```

```{r}
load("~/Library/CloudStorage/OneDrive-Personal/28PHD_peng/250301-DROMA_project/250119-DROMA_DB/Input/04/mRNA.Rda")
save(
  ccle_mRNA,
  gdsc_mRNA,
  NCI60_mRNA,
  tavor_mRNA,
  UMPDO1_mRNA,
  UMPDO2_mRNA,
  UMPDO3_mRNA,
  Xeva_mRNA,
  file = "Input/04/mRNA.Rda"
)
```


drugs:
```{r}
save(
  # PDC
  tavor_drug,
  PDTXBreast_drug,
  # CellLine
  ctrp1_drug,
  ctrp2_drug,
  gdsc1_drug,
  gdsc2_drug,
  gCSI_drug,
  prism_drug,
  FIMM_drug,
  UHNBreast_drug,
  GRAY_drug,
  NCI60_drug,
  ccle_drug,
  # PDO
  UMPDO1_drug,
  UMPDO2_drug,
  UMPDO3_drug,
  # PDX
  Xeva_drug,
  file = "Input/02/drug.Rda"
)
```


