```{r library, include=FALSE}
my_packages <- c("tidyverse", "data.table",
                 "ggpubr", "plotly",
                 "umap", "Rtsne",
                 "impute")
pacman::p_load(char = my_packages)

tmp <- list()
```

# Function
## MADMed
```{r}
calMADandMedian <- function(df){
  re <- apply(df, 1, function(x){
    md1 <- mad(x, na.rm = T)
    median1 <- median(x, na.rm = T)
    c(md1, median1)
  })
  re <- as.data.frame(t(re))
  colnames(re) <- c("Mad", "Median")
  re$Name <- rownames(re)
  re <- merge(re, drug_anno, 
                  by = "Name", all.x = T)
  return(re)
}
```

```{r}
plotMADandMedian <- function(ms, dataset){
  ms$Dataset <- dataset
  p <- ggplot(data = ms, 
            aes(text = Name, x = Mad,
                y = Median, label = Target, label2 = Dataset)) +
  geom_point(alpha=0.4, size=3.5, 
             aes(color=Phase)) + theme_bw() + 
  scale_color_manual(values = paletteer::paletteer_d("ggsci::default_igv")) + 
    labs(x = "MAD", y = "Median") + 
  theme(
            axis.title = element_text(size = 15),
            title = element_text(size = 15, face = "bold"),
            axis.text = element_text(size = 12), 
            legend.text = element_text(size = 12)
          )
  return(p)
}
```

## TSNE
```{r}
calTSNE <- function(df, perplexity = 25){
  drug <- df
  drug2 <- drug[apply(drug, 1, function(x){
    sum(is.na(x)) < 0.5*ncol(drug)
  }),apply(drug, 2, function(x){
    sum(is.na(x)) < 0.8*nrow(drug)
  })] 
  drug2 <- impute.knn(as.matrix(drug2))$data
  withr::with_seed(123, tsne_df <- Rtsne(drug2, dims = 2, 
                                    pca = TRUE,theta = 0.0,max_iter = 5000,perplexity = perplexity))
  tsne_df <- as.data.frame(tsne_df$Y)
  colnames(tsne_df) <- c("TSNE1", "TSNE2")
  tsne_df$Name <- rownames(drug2)
  tsne_df <- merge(tsne_df, drug_anno, 
                    by = "Name", all.x = T)
  return(tsne_df)
}

plotTSNE <- function(df, dataset){
  df$Dataset <- dataset
  p <- ggplot(data = df, 
            aes(text = Name, x = TSNE1,
                y = TSNE2, label = Target, label2 = Dataset)) +
    geom_point(alpha=0.4, size=3.5, 
               aes(color=Phase)) + theme_bw() + 
    scale_color_manual(values = paletteer::paletteer_d("ggsci::default_igv")) + 
    labs(x = "TSNE1", y = "TSNE2") + 
    theme(
              axis.title = element_text(size = 15),
              title = element_text(size = 15, face = "bold"),
              axis.text = element_text(size = 12), 
              legend.text = element_text(size = 12)
            )
  return(p)
}
```


# Load 
```{r}
load("Output/02/drug2.Rda")
load("Output/04/anno.Rda")
```

# mad_median
## gdsc1
```{r}
gdsc1_ms <- calMADandMedian(gdsc1_drug)
p_ms_gdsc1 <- plotMADandMedian(gdsc1_ms, dataset = "GDSC1")
p_ms_gdsc1
```

## gdsc2
```{r}
gdsc2_ms <- calMADandMedian(gdsc2_drug)
p_ms_gdsc2 <- plotMADandMedian(gdsc2_ms, dataset = "GDSC2")
p_ms_gdsc2
```

## prism
```{r}
prism_ms <- calMADandMedian(prism_drug)
p_ms_prism <- plotMADandMedian(prism_ms, dataset = "PRISM")
p_ms_prism
```

## ctrp1
```{r}
ctrp1_ms <- calMADandMedian(ctrp1_drug)
p_ms_ctrp1 <- plotMADandMedian(ctrp1_ms, dataset = "CTRP1")
p_ms_ctrp1
```

## ctrp2
```{r}
ctrp2_ms <- calMADandMedian(ctrp2_drug)
p_ms_ctrp2 <- plotMADandMedian(ctrp2_ms, dataset = "CTRP2")
p_ms_ctrp2
```

## gCSI
```{r}
gCSI_ms <- calMADandMedian(gCSI_drug)
p_ms_gCSI <- plotMADandMedian(gCSI_ms, dataset = "gCSI")
p_ms_gCSI
```

# Dimension reduction
Ref: Exploring subclass-specific therapeutic agents for hepatocellular carcinoma by informatics-guided drug screen

Filter drugs with more than 50% missing data.

## gdsc1
```{r}
# apply(gdsc1_drug, 1, function(x){
#   sum(is.na(x))/ncol(gdsc1_drug)
# })
```

```{r}
gdsc1_tsne <- calTSNE(gdsc1_drug)
p_tsne_gdsc1 <- plotTSNE(gdsc1_tsne, dataset = "GDSC1")
p_tsne_gdsc1
```

## gdsc2
```{r}
gdsc2_tsne <- calTSNE(gdsc2_drug)
p_tsne_gdsc2 <- plotTSNE(gdsc2_tsne, dataset = "GDSC2")
p_tsne_gdsc2
```

## prism
```{r}
prism_tsne <- calTSNE(prism_drug)
p_tsne_prism <- plotTSNE(prism_tsne, dataset = "PRISM")
p_tsne_prism
```

## ctrp1
```{r}
ctrp1_tsne <- calTSNE(ctrp1_drug)
p_tsne_ctrp1 <- plotTSNE(ctrp1_tsne, dataset = "CTRP1")
p_tsne_ctrp1
```

## ctrp2
```{r}
ctrp2_tsne <- calTSNE(ctrp2_drug)
p_tsne_ctrp2 <- plotTSNE(ctrp2_tsne, dataset = "CTRP2")
p_tsne_ctrp2
```

## gCSI
```{r}
gCSI_tsne <- calTSNE(gCSI_drug, perplexity = 5)
p_tsne_gCSI <- plotTSNE(gCSI_tsne, dataset = "gCSI")
p_tsne_gCSI
```

# Save
## plot
```{r}
save(gdsc1_ms,gdsc2_ms,
     prism_ms, gCSI_ms,
     ctrp1_ms, ctrp2_ms, # mad_median
     gdsc1_tsne, gdsc2_tsne,
     prism_tsne, gCSI_tsne,
     ctrp1_tsne, ctrp2_tsne, # tsne
     file = "Output/05/drug_sens_profile.Rda")
```


